### ISSUE TITLE
Error: Provided OSRM directory does not seem to be correct!

### ISSUE THREAD

**Issue by flozanor82** [christophrust/osrmtime#1]
Dear Christopher,

I am setting up the Linux environment for HC in my University to use osrm from stata. I apologize if this has been asked before, however, I have been reading a while and I have not managed to find the appropriate OSRM Directory to prepare the downloaded maps.

Do you know if there is there a way to find the directory? Thanks in advance for your help.
Best regards,

Felipe Lozano

**Comment by christophrust** [comment]
Dear Felipe,

Sorry for my late reply!

Did you follow the installation instructions for OSRM? If you've run `make-install`, it is quite likely that osrm is in your system path and you should be able to obtain its location if you enter `which osrm-routed` in a terminal.

I also updated the code (See [a495922](https://github.com/christophrust/osrmtime/commit/a495922befe710f492bbe2085f18b7baa9ef9904)) a little bit such that it now looks at some standard locations, including the system path, for the executable.

Sorry once more for my late reply!
Best,
Christoph
